### ISSUE TITLE
AttributeError: 'module' object has no attribute 'run'

### ISSUE THREAD

**Issue by mictadlo** [vpc-ccg/haslr#31]
Hi,

```
git clone https://github.com/vpc-ccg/haslr.git
cd haslr
make
```

```
export PATH=/work/team/apps/haslr/bin/:$PATH

checking /work/team/apps/haslr/bin/haslr_assemble: Traceback (most recent call last):
  File "/work/team/apps/haslr/bin/haslr.py", line 381, in <module>
    main()
  File "/work/team/apps/haslr/bin/haslr.py", line 25, in main
    check_program(path_haslr_assemble)
  File "/work/team/apps/haslr/bin/haslr.py", line 271, in check_program
    completed = subprocess.run([prog, '-h'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
AttributeError: 'module' object has no attribute 'run'
```

What did I miss?

**Comment by Kirstie-dev** [comment]
check:
python --version
You need python3
